export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'



export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const CHANGE_PAGE = 'CHANGE_PAGE'


export const CREATE_LISTING_BEGIN = 'CREATE_LISTING_BEGIN'
export const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS'
export const CREATE_LISTING_ERROR = 'CREATE_LISTING_ERROR'

export const GET_LISTINGS_BEGIN = 'GET_LISTINGS_BEGIN'
export const GET_LISTINGS_SUCCESS = 'GET_LISTINGS_SUCCESS'
export const GET_LISTINGS_ERROR = 'GET_LISTINGS_ERROR'

export const GET_AUTHLISTINGS_BEGIN = 'GET_AUTHLISTINGS_BEGIN'
export const GET_AUTHLISTINGS_SUCCESS = 'GET_AUTHLISTINGS_SUCCESS'
export const GET_AUTHLISTINGS_ERROR = 'GET_AUTHLISTINGS_ERROR'

export const GET_SINGLELISTING_BEGIN = 'GET_SINGLELISTING_BEGIN'
export const GET_SINGLELISTING_SUCCESS = 'GET_SINGLELISTING_SUCCESS'
export const GET_SINGLELISTING_ERROR = 'GET_SINGLELISTING_ERROR'

export const CREATE_ORDER_BEGIN = 'CREATE_ORDER_BEGIN'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'


export const GET_BOOKINGS_BEGIN = 'GET_BOOKINGS_BEGIN';
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';


